- name: Update global credential "{{ item['id'] }}"
  environment:
    JENKINS_AUTH: "{{ jenkins_admin_username }}:{{ jenkins_admin_password }}"
  shell: "{{ lookup('template', 'jenkins-cli.j2') }} update-credentials-by-xml 'SystemCredentialsProvider::SystemContextResolver::jenkins' _ {{ item['id'] }}"
  args:
    chdir: "{{ jenkins_home }}"
    stdin: "{{ lookup('template', 'credential.xml.j2') }}"
  register: cred_update_result
  failed_when: cred_update_result.rc != 0 and cred_update_result.rc != 3
  changed_when: cred_update_result.rc == 0

- name: Create global credential "{{ item['id'] }}"
  environment:
    JENKINS_AUTH: "{{ jenkins_admin_username }}:{{ jenkins_admin_password }}"
  shell: "{{ lookup('template', 'jenkins-cli.j2') }} create-credentials-by-xml 'SystemCredentialsProvider::SystemContextResolver::jenkins' _"
  args:
    chdir: "{{ jenkins_home }}"
    stdin: "{{ lookup('template', 'credential.xml.j2') }}"
  when: cred_update_result.rc == 3
  # register: cred_result
  # failed_when: cred_create_result.rc != 0 and cred_create_result.stderr != "No change"
  # changed_when: cred_create_result.rc == 0
